[package]
name = "zero2prod"
version = "0.1.0"
edition = "2024"

[lib]
path = "src/lib.rs"

[[bin]]
path = "src/main.rs"
name = "zero2prod"

[dependencies]
axum = "0.8.8"
chrono = { version = "0.4.44", default-features = false, features = ["clock"] }
config = { version = "0.15.22", default-features = false, features = ["yaml"] }
serde = { version = "1.0.228", features = ["derive"] }
sqlx = { version = "0.8.6", default-features = false, features = ["runtime-tokio-rustls", "macros", "postgres", "uuid", "chrono", "migrate"] }
tokio = { version = "1.50.0", features = ["macros", "rt-multi-thread", "signal"] }
tracing = { version = "0.1.44", features = ["log"] }
tracing-log = "0.2.0"
tracing-subscriber = { version = "0.3.23", features = ["registry", "fmt", "env-filter", "json"] }
uuid = { version = "1.23.0", default-features = false, features = ["v7", "rng", "serde"] }

[dev-dependencies]
reqwest = "0.13.2"

