itg-test target="*":
  cargo test --test '{{target}}'

gdiff:
  git diff -- . ':(exclude)Cargo.lock'

dbshell db_container_name="newsletter_axum_postgres" db_name="newsletter":
  docker exec -it {{db_container_name}} psql -U postgres -d {{db_name}}

