set dotenv-load := true

itest target="*" fn="":
  cargo test --test '{{target}}' -- {{fn}}

gdiff:
  git diff -- . ':(exclude)Cargo.lock'

# NOTE: Docker commands
doc-dbshell db_container_name="newsletter_axum_postgres" db_name="newsletter":
  docker exec -it {{db_container_name}} psql -U postgres -d {{db_name}}

# NOTE: Fly.io commands
fly-ssh:
  fly ssh console

# TODO: fly-app-scale2zero:

fly-web-start:
  fly machine start -a $REMOTE_APP_NAME

fly-web-suspend:
  fly machine suspend -a $REMOTE_APP_NAME


fly-db-start:
  fly machine start -a $REMOTE_DB_NAME

fly-db-suspend:
  fly machine suspend -a $REMOTE_DB_NAME

fly-db-proxy:
  fly proxy 15432:5432 -a $REMOTE_DB_NAME

fly-psql:
  psql $REMOTE_PROXY_DB_URL

fly-migrate:
  DATABASE_URL=$REMOTE_PROXY_DB_URL sqlx migrate run

